
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE := rsync
LOCAL_DESCRIPTION := Utility that provides fast incremental file transfer.
LOCAL_CATEGORY_PATH := devel

LOCAL_AUTOTOOLS_VERSION := 3.1.2
LOCAL_AUTOTOOLS_ARCHIVE := $(LOCAL_MODULE)-$(LOCAL_AUTOTOOLS_VERSION).tar.gz
LOCAL_AUTOTOOLS_SUBDIR := $(LOCAL_MODULE)-$(LOCAL_AUTOTOOLS_VERSION)

LOCAL_AUTOTOOLS_MAKE_BUILD_ARGS := -j 1

include $(BUILD_AUTOTOOLS)

